spring:
  application:
    name: carrier-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/soluctiondb}
    username: ${SPRING_DATASOURCE_USERNAME:soluction}
    password: ${SPRING_DATASOURCE_PASSWORD:soluction}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
  redis:
    host: localhost
    port: 6379
server:
  port: 8080
  servlet:
    context-path: /carrier-service
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
cloud:
  aws:
    region:
      static: us-east-1
    stack:
      auto: false
    credentials:
      useDefaultAwsCredentialsChain: true
      access-key: test
      secret-key: test
    sqs:
      endpoint: ${SPRING_LOCALSTACK_HOST:https://localhost.localstack.cloud:4566/000000000000}


card-sqs-name: ${SPRING_CARD_SQS_NAME:https://localhost.localstack.cloud:4566/000000000000/cards-register}
carrier:
  keysecret: '8R9SATCVDWEYGZH2K4M5N7Q8R9TBUCVEXFYG2J3K4N6P7Q8SATBUDWEXFZ'

card-service: ${SPRING_CARD_SERVICE_URL:http://localhost:8081/card-service}

sqs-url: ${SPRING_LOCALSTACK_HOST:https://localhost.localstack.cloud:4566/000000000000}

